apiVersion: apps/v1
kind: Deployment
metadata:
  name: books-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: books-deployment
  template:
    metadata:
      labels:
        app: books-deployment
    spec:
      containers: 
      - name: books-deployment
        image: $CONTAINER_REGISTRY/book_catalog:$VERSION
        imagePullPolicy: Always
        env:
        - name: DATABASE_URL
          value: "postgresql://postgres:$POSTGRESQL_PASSWORD@somethinglocal/postgres"
---
apiVersion: v1
kind: Service
metadata:
  name: books-service
spec:
  selector:
    app: books-deployment
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-deployment
  template:
    metadata:
      labels:
        app: inventory-deployment
    spec:
      containers:
      - name: inventory-deployment
        image: $CONTAINER_REGISTRY/inventory_management:$VERSION
        imagePullPolicy: Always
        env:
        - name: DATABASE_URL
          value: "postgresql://postgres:$POSTGRESQL_PASSWORD@somethinglocal/postgres"
---
apiVersion: v1
kind: Service
metadata:
  name: inventory-service
spec:
  selector:
    app: inventory-deployment
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000

