name: App Deployment

on:
  # push: 
  #   branches:
  #     - main
  workflow_dispatch: 

permissions:
  id-token: write
  contents: read

jobs:
  eploy-container-workloads:
    name: 'Deploy Application'
    runs-on: ubuntu-latest
    env:
      VERSION: ${{ github.sha }}
      CONTAINER_REGISTRY: ${{ secrets.CONTAINER_REGISTRY }}
      # REGISTRY_UN: ${{ secrets.REGISTRY_UN }}
      # REGISTRY_PW: ${{ secrets.REGISTRY_PW  }}
      POSTGRESQL_PASSWORD: ${{ secrets.POSTGRESQL_PASSWORD }}

    steps:
    - name: Azure login
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Login to K8s
      run: az aks get-credentials --resource-group ninetwodistinction --name ninetwodistinction
      
    - name: Checkout
      uses: actions/checkout@v4

    - name: Build
      run: ./scripts/build-image.sh

    - name: Publish
      run: ./scripts/push-image.sh

      ## Login

    - name: Deploy
      run: ./scripts/deploy.sh
