name: Deployment

on:
  # push: 
  #   branches:
  #     - main
  workflow_dispatch: 

permissions:
  id-token: write
  contents: read

jobs:
  deploy-terraform-infra:
    name: 'Terraform Plan'
    runs-on: ubuntu-latest

    steps:
    - name: Azure login
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Terraform Init
      working-directory: ./create_k8s
      run: terraform init
      
    - name: Terraform Apply
      working-directory: ./create_k8s
      run: terraform apply -auto-approve

  # deploy-container-workloads:
  #   runs-on: ubuntu-latest
    
  #   env:
  #     # CONTAINER_REGISTRY: ${{ secrets.CONTAINER_REGISTRY }}
  #     # REGISTRY_UN: ${{ secrets.REGISTRY_UN }}
  #     # REGISTRY_PW: ${{ secrets.REGISTRY_PW  }}
  #     POSTGRESQL_PASSWORD: ${{ secrets.POSTGRESQL_PASSWORD }}

  #   steps:
  #   - name: Azure login
  #     uses: azure/login@v2
  #     with:
  #       client-id: ${{ secrets.AZURE_CLIENT_ID }}
  #       tenant-id: ${{ secrets.AZURE_TENANT_ID }}
  #       subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    
  #   - name: Checkout
  #     uses: actions/checkout@v4

  #   - name: Build
  #     run: ./scripts/build-image.sh

  #   - name: Publish
  #     run: ./scripts/push-image.sh

  #   - uses: tale/kubectl-action@v1
  #     with:
  #       base64-kube-config: ${{ secrets.KUBE_CONFIG }}

  #   - name: Deploy
  #     run: ./scripts/deploy.sh
